### ISSUE TITLE
channel closed exception on agent launch

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-agent#101]
```
2018-08-21T09:35:05.117Z interactor:daemon MACHINE_NAME=wakanda-5c0b
2018-08-21T09:35:05.137Z interactor:daemon PUBLIC_KEY=tisf3wwdixc3eud
2018-08-21T09:35:05.139Z interactor:daemon WEBSOCKET_ENABLED=false
2018-08-21T09:35:05.140Z interactor:daemon AXON_ENABLED=true
2018-08-21T09:35:05.140Z interactor:daemon ROOT_URL=https://root.keymetrics.io
2018-08-21T09:35:05.142Z interactor:interface New transporter interface
2018-08-21T09:35:05.145Z interactor:interface Bind [axon] transport to transporter interface
2018-08-21T09:35:05.324Z interactor:daemon [PM2 Agent] Launching agent
2018-08-21T09:35:05.327Z interactor:daemon Launching Interactor RPC server (bind to /home/pi/.pm2/interactor.sock)
2018-08-21T09:35:16.432Z interactor:daemon Send to process daemon is started
2018-08-21T09:35:16.467Z interactor:reverse Reverse interactor is listening
2018-08-21T09:35:16.468Z interactor:daemon Interactor daemon started
-- FATAL EXCEPTION happened --
2018-08-21T09:35:16.477Z
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:627:16)
    at verifyEndpointCallback (/usr/lib/node_modules/pm2/node_modules/@pm2/agent/src/InteractorDaemon.js:338:17)
    at async.each (/usr/lib/node_modules/pm2/node_modules/@pm2/agent/src/TransporterInterface.js:79:7)
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:992:24)
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:969:16
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:3888:9
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:1064:13)
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:969:16
Re-initiating Agent
[PM2 Agent] Using (Public key: tisf3wwdixc3eud) (Private key: 9wabee4a74lc5u3) (Info node: https://root.keymetrics.io)
2018-08-21T09:35:16.736Z interactor:pm2:interface PM2Interface instantiate
2018-08-21T09:35:18.260Z interactor:daemon MACHINE_NAME=wakanda-5c0b
2018-08-21T09:35:18.280Z interactor:daemon PUBLIC_KEY=tisf3wwdixc3eud
2018-08-21T09:35:18.282Z interactor:daemon WEBSOCKET_ENABLED=false
2018-08-21T09:35:18.283Z interactor:daemon AXON_ENABLED=true
2018-08-21T09:35:18.283Z interactor:daemon ROOT_URL=https://root.keymetrics.io
2018-08-21T09:35:18.285Z interactor:interface New transporter interface
2018-08-21T09:35:18.290Z interactor:interface Bind [axon] transport to transporter interface
2018-08-21T09:35:18.427Z interactor:daemon [PM2 Agent] Launching agent
2018-08-21T09:35:18.430Z interactor:daemon Launching Interactor RPC server (bind to /home/pi/.pm2/interactor.sock)
2018-08-21T09:35:21.724Z interactor:daemon Send to process daemon is started
2018-08-21T09:35:21.735Z interactor:client Interactor daemon launched : { error: false,
  km_data:
   { endpoints:
      { push: 'https://lambda.keymetrics.io:80',
        ws: 'wss://lambda.keymetrics.io/interaction/public',
        reverse: 'https://lambda.keymetrics.io:43554',
        realtime: 'https://lambda.keymetrics.io:443',
        web: 'https://lambda.keymetrics.io:443' },
     new: false,
     active: true,
     pending: false,
     disabled: false },
  online: true,
  pid: 2345,
  machine_name: 'wakanda-5c0b',
```

**Comment by Unitech** [comment]
Seems that 

```
  // send data over IPC for CLI feedback                                                                                                                                                                        
      if (process.send) {
	log('Send to process daemon is started')
        process.send({
          error: false,
          km_data: this.km_data,
          online: true,
          pid: process.pid,
          machine_name: this.opts.MACHINE_NAME,
          public_key: this.opts.PUBLIC_KEY,
          secret_key: this.opts.SECRET_KEY,
          reverse_interaction: this.opts.REVERSE_INTERACT
        })
      }
```

is not sufficient to check that the child process can send a message to his parent

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/blob/29cccd9437e75e36f56d1afb0de3d73a5d033d21/lib/ProcessContainerFork.js#L21
