### ISSUE TITLE
After reconnect from another network, agent fail

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-agent#106]
```
2018-08-27T17:42:25.701Z interactor:watchdog Launching
2018-08-27T20:00:02.318Z interactor:daemon Got an a error on ping root { Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'root.keymetrics.io',
  host: 'root.keymetrics.io',
  port: 443 }
^C
```

**Comment by Unitech** [comment]
not duplicate, this happened again while I was connected home, when I went back to the office the agent lost his connectivity with this error:

```
2018-08-27T20:12:27.210Z interactor:daemon PM2 Watchdog started
2018-08-27T20:12:27.211Z interactor:watchdog Launching
2018-08-28T06:44:08.619Z interactor:daemon Got an a error on ping root { Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'root.keymetrics.io',
  host: 'root.keymetrics.io',
  port: 443 }
2018-08-28T06:44:13.640Z interactor:transporter Closed transporter
2018-08-28T06:44:13.641Z interactor:transporter Trying to reconnect to remote endpoint
2018-08-28T06:44:13.642Z interactor:interface Received event from websocket transporter
2018-08-28T06:44:13.685Z interactor:transporter Internet is reachable again
2018-08-28T06:44:13.885Z interactor:transporter Connection etablished with remote endpoint
```

**Comment by vmarchaud** [comment]
We can see that the agent reconnect afterwards from the logs, i don't see the issue here. it's normal that the agent fail to do the dns request when the network is down, it still attempt it in the background

**Comment by Unitech** [comment]
I will try to reproduce again, but it was not reconnecting even if written (the logs was stopped at that point)
