### ISSUE TITLE
@pm2/agent missing dependency on chalk

### ISSUE THREAD

**Issue by irnc** [keymetrics/pm2-io-agent#116]
## What's going wrong?

`pm2-runtime` errors on specific node_modules layout when modules are installed using npm@6.5.0

```
> pm2-runtime start pm2.json --env=production

module.js:550
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/node_modules/@pm2/agent/src/InteractorClient.js:8:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

## How could we reproduce this issue?

```
npm init -y
npm i chalk@1.0 --save-dev
npm i pm2@3.2.4
rm -rf node_modules
npm i --production
npx pm2-runtime
```

The last line would be `Cannot find module 'chalk'`.

## Supporting information

This error happens because `@pm2/agent` requires `chalk`, but doesn't list it as a dependency (it lists it as a devDependency). Usually this issue doesn't cause an error because `chalk` from `pm2` dependencies are hoisted to `node_modules/chalk` by npm CLI, thus making it available to `node_modules/@pm2/agent`

It is essential that quite old `chalk` package is marked with `{ dev: true }` at root-level dependencies of `package-lock.json`. This prevents `chalk` dependency of `pm2` to be hoisted at `node_modules/chalk` by npm CLI. While `npm i --production` prevents installation of devDependency chalk.

**Comment by Eywek** [comment]
Thank's for the report, it should be fixed with [v0.5.21](https://github.com/keymetrics/pm2-io-agent/releases/tag/v0.5.21).
