### ISSUE TITLE
RangeError: "port" option should be >= 0 and < 65536: NaN

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-agent#85]
Node 6
Ubuntu 16.04.4 LTS

https://github.com/keymetrics/pm2-io-agent/blob/master/src/transporters/AxonTransport.js#L107

```
-- FATAL EXCEPTION happened --
-- FATAL EXCEPTION happened --
2018-07-06T15:57:31.681Z
RangeError: "port" option should be >= 0 and < 65536: NaN
    at lookupAndConnect (net.js:960:13)
    at Socket.connect (net.js:935:5)
    at Socket.connect (net.js:898:37)
    at PubSocket.Socket.connect (/usr/lib/node_modules/pm2/node_modules/pm2-axon/lib/sockets/sock.js:296:8)
    at async.parallel (/usr/lib/node_modules/pm2/node_modules/@pm2/agent/src/transporters/AxonTransport.js:107:28)
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:3880:24
    at eachOfArrayLike (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:1069:9)
    at eachOf (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:1117:5)
    at _parallel (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:3879:5)
    at Object.parallelLimit [as parallel] (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:3962:5)
2018-07-06T15:57:31.683Z
```

**Comment by Eywek** [comment]
Can you log endpoints here https://github.com/keymetrics/pm2-io-agent/blob/master/src/InteractorDaemon.js#L262 (`data.endpoints`)

**Comment by Eywek** [comment]
can we ask to users with this bug to reproduce with development branch? I've added more logs, it will be more easy to debug
