### ISSUE TITLE
Fatal errors

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-agent#88]
```
2018-07-23T15:40:48.780Z interactor:daemon Send to process daemon is started
2018-07-23T15:40:48.781Z interactor:client Interactor daemon launched : { error: false,
  km_data:
   { endpoints:
      { push: 'https://tau.keymetrics.io:80',
        ws: 'wss://tau.keymetrics.io/interaction/public',
        reverse: 'https://tau.keymetrics.io:43554',
        realtime: 'https://tau.keymetrics.io:443',
        web: 'https://tau.keymetrics.io:443' },
     new: false,
     active: true,
     pending: false,
     disabled: false },
  online: true,
  pid: 12492,
  machine_name: 'zion-bec7',
  public_key: 'yffi9bxeiz53hsn',
  secret_key: 'ub216fps' }
2018-07-23T15:40:48.783Z interactor:reverse Reverse interactor is listening
2018-07-23T15:40:48.783Z interactor:daemon Interactor daemon started
Succesfully launched new agent
-- FATAL EXCEPTION happened --
2018-07-23T15:40:49.173Z
TypeError: this._daemon.getPM2Client(...).rpc.getMonitorData is not a function
    at AxonTransport.preparePacket (/home/unitech/keymetrics/pm2/node_modules/@pm2/agent/src/transporters/AxonTransport.js:183:37)
    at AxonTransport._send (/home/unitech/keymetrics/pm2/node_modules/@pm2/agent/src/transporters/AxonTransport.js:221:10)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
Re-initiating Agent
[PM2 Agent] Using (Public key: yffi9bxeiz53hsn) (Private key: ub2e16fps) (Info node: https://root.keymetrics.io)
[PM2 Agent] Launching agent
2018-07-23T15:40:49.344Z interactor:daemon MACHINE_NAME=zion-bec7
2018-07-23T15:40:49.344Z interactor:daemon PUBLIC_KEY=yffi9bxeiz53hsn
````

**Comment by Unitech** [comment]
published 0.5.11
