### ISSUE TITLE
agent crash and root.keymetrics.io not reachable

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pm2-io-agent#99]
Agent 0.5.12
on wakanda.local

```
2018-08-21T08:17:23.486Z interactor:daemon ROOT_URL=https://root.keymetrics.io
2018-08-21T08:17:23.487Z interactor:interface New transporter interface
2018-08-21T08:17:23.489Z interactor:interface Bind [axon] transport to transporter interface
2018-08-21T08:17:23.622Z interactor:daemon [PM2 Agent] Launching agent
2018-08-21T08:17:23.624Z interactor:daemon Launching Interactor RPC server (bind to /home/pi/.pm2/interactor.sock)
2018-08-21T08:17:23.812Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:23.814Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:23.815Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:17:24.035Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:24.036Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:24.036Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:17:24.446Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:24.447Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:24.447Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:17:25.058Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:25.058Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:25.058Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:17:25.867Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:25.868Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:25.868Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:17:26.898Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:26.900Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:26.901Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:17:28.131Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:28.133Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:28.134Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:17:29.558Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:29.559Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:29.559Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:17:31.179Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:31.180Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:31.181Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:17:32.999Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:33.000Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:33.001Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:17:35.014Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:35.015Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:35.016Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:17:37.226Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:37.226Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:37.227Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:17:39.657Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:39.659Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:39.660Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:17:42.272Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:42.273Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:42.273Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:17:45.083Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:45.084Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:45.084Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:17:48.098Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:48.098Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:48.099Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:17:51.330Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:51.332Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:51.333Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:17:54.744Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:54.744Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:54.745Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:17:58.377Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:58.379Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:17:58.380Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:18:02.190Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:18:02.190Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:18:02.191Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:18:06.246Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:18:06.249Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:18:06.250Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:18:10.461Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:18:10.461Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:18:10.462Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:18:14.871Z interactor:daemon Got an a error on ping root Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:18:14.871Z interactor:daemon Error while trying to retrieve endpoints : Error: getaddrinfo ENOTFOUND root.keymetrics.io root.keymetrics.io:443
2018-08-21T08:18:14.872Z interactor:daemon Retrying to retrieve endpoints...
2018-08-21T08:18:24.790Z interactor:daemon Send to process daemon is started
2018-08-21T08:18:24.811Z interactor:reverse Reverse interactor is listening
2018-08-21T08:18:24.812Z interactor:daemon Interactor daemon started
-- FATAL EXCEPTION happened --
2018-08-21T08:18:24.819Z
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:627:16)
    at verifyEndpointCallback (/usr/lib/node_modules/pm2/node_modules/@pm2/agent/src/InteractorDaemon.js:338:17)
    at async.each (/usr/lib/node_modules/pm2/node_modules/@pm2/agent/src/TransporterInterface.js:79:7)
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:992:24)
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:969:16
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:3888:9
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:1064:13)
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:969:16
Re-initiating Agent
[PM2 Agent] Using (Public key: tisf3wwdixc3eud) (Private key: 9wabee4a74lc5u3) (Info node: https://root.keymetrics.io)
2018-08-21T08:18:24.964Z interactor:pm2:interface PM2Interface instantiate
2018-08-21T08:18:26.243Z interactor:daemon MACHINE_NAME=wakanda-5c0b
2018-08-21T08:18:26.257Z interactor:daemon PUBLIC_KEY=tisf3wwdixc3eud
2018-08-21T08:18:26.258Z interactor:daemon WEBSOCKET_ENABLED=false
2018-08-21T08:18:26.258Z interactor:daemon AXON_ENABLED=true
2018-08-21T08:18:26.259Z interactor:daemon ROOT_URL=https://root.keymetrics.io
2018-08-21T08:18:26.260Z interactor:interface New transporter interface
2018-08-21T08:18:26.262Z interactor:interface Bind [axon] transport to transporter interface
2018-08-21T08:18:26.382Z interactor:daemon [PM2 Agent] Launching agent
2018-08-21T08:18:26.385Z interactor:daemon Launching Interactor RPC server (bind to /home/pi/.pm2/interactor.sock)
[PM2.IO][WARNING] Not managed to connect to PM2 Plus, retrying in background.
2018-08-21T08:18:31.878Z interactor:daemon Succesfully launched new agent
2018-08-21T08:18:31.879Z interactor:daemon Exiting Interactor
2018-08-21T08:18:31.882Z interactor:reverse Reverse interactor is no longer listening
2018-08-21T08:18:31.889Z interactor:interface Disconnect all transporters
2018-08-21T08:18:31.910Z interactor:daemon RPC server closed
2018-08-21T09:04:07.483Z interactor:daemon Send to process daemon is started
2018-08-21T09:04:07.526Z interactor:reverse Reverse interactor is listening
2018-08-21T09:04:07.527Z interactor:daemon Interactor daemon started
-- FATAL EXCEPTION happened --
2018-08-21T09:04:07.539Z
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:627:16)
    at verifyEndpointCallback (/usr/lib/node_modules/pm2/node_modules/@pm2/agent/src/InteractorDaemon.js:338:17)
    at async.each (/usr/lib/node_modules/pm2/node_modules/@pm2/agent/src/TransporterInterface.js:79:7)
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:992:24)
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:969:16
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:3888:9
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/usr/lib/node_modules/pm2/node_modules/async/dist/async.js:1064:13)
    at /usr/lib/node_modules/pm2/node_modules/async/dist/async.js:969:16
Re-initiating Agent
[PM2 Agent] Using (Public key: tisf3wwdixc3eud) (Private key: 9wabee4a74lc5u3) (Info node: https://root.keymetrics.io)
-- FATAL EXCEPTION happened --
2018-08-21T09:04:07.652Z
TypeError: this._daemon.getPM2Client(...).rpc.getMonitorData is not a function
    at AxonTransport.preparePacket (/usr/lib/node_modules/pm2/node_modules/@pm2/agent/src/transporters/AxonTransport.js:183:37)
    at AxonTransport._send (/usr/lib/node_modules/pm2/node_modules/@pm2/agent/src/transporters/AxonTransport.js:221:10)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
Re-initiating Agent
[PM2 Agent] Using (Public key: tisf3wwdixc3eud) (Private key: 9wabee4a74lc5u3) (Info node: https://root.keymetrics.io)
2018-08-21T09:04:07.716Z interactor:pm2:interface PM2Interface instantiate
2018-08-21T09:04:09.092Z interactor:daemon MACHINE_NAME=wakanda-5c0b
2018-08-21T09:04:09.107Z interactor:daemon PUBLIC_KEY=tisf3wwdixc3eud
2018-08-21T09:04:09.109Z interactor:daemon WEBSOCKET_ENABLED=false
```

**Comment by vmarchaud** [comment]
Same issue as https://github.com/keymetrics/pm2-io-agent/issues/92 right ?

**Comment by Unitech** [comment]
Looks similar + this exception:

```
2018-08-21T09:04:07.652Z
TypeError: this._daemon.getPM2Client(...).rpc.getMonitorData is not a function
    at AxonTransport.preparePacket (/usr/lib/node_modules/pm2/node_modules/@pm2/agent/src/transporters/AxonTransport.js:183:37)
    at AxonTransport._send (/usr/lib/node_modules/pm2/node_modules/@pm2/agent/src/transporters/AxonTransport.js:221:10)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

I can't get how the root.keymetrics.io is unreachable. Can't we do the DNS load balancing on Route 53 to hit each node available?

**Comment by vmarchaud** [comment]
We could but some people have firewall in place and it may stop working for them, its a risky move
